Features/dsb 131
lianetoolkit/liane-toolkit pull request #165
Opened 2020-09-18 10:50 UTC by nefertiter

- Close task #131

2020-09-21 14:30 UTC, miguelpeixe requested changes
Here are some required changes from a quick reading of the code

2020-09-21 14:30 UTC, miguelpeixe commented on imports/api/dashboard/server/dashboardMethods.js
> +        const redisKey = `dashboard.${facebookAccountId}.chartsData`;
The key should contain date information to filtering options. This key and its verification below would always retrieve the same data.

2020-09-21 14:30 UTC, miguelpeixe commented on imports/api/dashboard/server/dashboardMethods.js
> +            chartsData = {
Missing storing data to redis

2020-09-21 14:30 UTC, miguelpeixe commented on imports/api/dashboard/server/dashboardMethods.js
> +    validate: new SimpleSchema({
There should be the following types of filter:

 - Last 7 days
 - This month
 - Past 30 days
 - Past 3 months

This can also be set on the frontend. By setting on the frontend, the only required parameter would be a "starting date". The starting date validation should only verify if its more recent than 90 days.

2020-09-21 20:17 UTC, nefertiter commented on imports/api/dashboard/server/dashboardMethods.js
> +    validate: new SimpleSchema({
@miguelpeixe  I will expect startDate and endDate for chartData, top comments and top reactions will be stored separately

2020-09-21 20:29 UTC, miguelpeixe commented
Redis storage should be as following:

## Top people

Top commenters and reactioners should be stored in `dashboard.${facebookAccount}.topPeople` with default object storing with expiration. 

## Charts

Charts data should be stored in `dashboard.${facebookAcount}.chartsData` with no expiration. The object containing `YYYY-MM-DD` keys should be updated according the current date and entries older than 90 days should be removed. Should return a filtered (according to the requested date) ordered (ascending date) array. The date (which was the object key) should be placed at a `date` key inside the array object.

2020-09-21 20:31 UTC, miguelpeixe commented
@nefertiter what do you think about top people also being updated according to the required date? It would probably change the logic behind this query.

2020-09-21 20:34 UTC, miguelpeixe commented on imports/api/dashboard/server/dashboardMethods.js
> +    validate: new SimpleSchema({
There's no need for endDate, the end date will always be yesterday.

2020-09-21 20:35 UTC, miguelpeixe commented on imports/api/dashboard/server/dashboardMethods.js
> +    validate: new SimpleSchema({
You can have the endDate, if you'd like, but i'd put it as an optional parameter with default value to yesterday.

2020-10-05 09:24 UTC, nefertiter commented on imports/api/dashboard/server/dashboardMethods.js
> +            chartsData = {
Updated in line 432.

2020-10-05 09:24 UTC, nefertiter commented on imports/api/dashboard/server/dashboardMethods.js
> +    validate: new SimpleSchema({
I've added the option 
`let end = new Date(endDate ?? moment().subtract(1).format("YYYY-MM-DD"))`

2020-10-05 09:26 UTC, nefertiter commented
> @nefertiter what do you think about top people also being updated according to the required date? It would probably change the logic behind this query.

Likely the queries should be updated, its just a bit tricky for me to work with no much data, but if its required or we see the case when we needed I can update the queries

2020-10-21 15:27 UTC, merged