Adding Instagram Support
lianetoolkit/liane-toolkit pull request #166
Opened 2020-09-30 12:36 UTC by mdegrati

2020-09-30 13:37 UTC, miguelpeixe requested changes
Here's a first review after a quick look through the code. Soon I'll go through further tests.

2020-09-30 13:37 UTC, miguelpeixe commented on .gitignore
> -node_modules/
Why was this line removed?

2020-09-30 13:37 UTC, miguelpeixe commented on imports/api/facebook/comments/comments.js
> +  source_data: {
This should be a `blackbox` object

2020-09-30 13:37 UTC, miguelpeixe commented on imports/api/facebook/comments/server/commentsHelpers.js
> +      comment.name = PeopleHelpers.getPersonName({ campaignId, instagramHandle: comment.username });
We should be using the `user_id` provided by Instagram. The instagram handle cannot be considered an ID since it can be changed.

2020-09-30 13:37 UTC, miguelpeixe commented on imports/api/facebook/entries/entries.js
> +  source_data: {
This should be a `blackbox` object

2020-09-30 13:37 UTC, miguelpeixe commented on imports/api/facebook/people/server/peopleHelpers.js
> +  getPersonId({ campaignId, instagramHandle }) {
We should use the `user_id` provided by Instagram. Instagram handle cannot be considered an ID

2020-09-30 13:37 UTC, miguelpeixe commented on imports/ui2/pages/Comments.jsx
> +    id: "app.comments.entry_select_placeholder",
The i18n ID must be unique, something like `app.comments.source_select_placeholder`

2020-10-17 11:48 UTC, mdegrati commented
Hola Miguel, como estas ?

Podremos coordinar como para reunirnos unos minutos el Lunes o Martes por
la tarde ?

Saludos,
Martin.-


El mié., 30 de sep. de 2020 a la(s) 10:37, Miguel Peixe (
notifications@github.com) escribió:

> *@miguelpeixe* requested changes on this pull request.
>
> Here's a first review after a quick look through the code. Soon I'll go
> through further tests.
> ------------------------------
>
> In .gitignore
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497506368>
> :
>
> > @@ -1,4 +1,3 @@
> -node_modules/
>
> Why was this line removed?
> ------------------------------
>
> In imports/api/facebook/comments/comments.js
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497508187>
> :
>
> > @@ -109,6 +109,26 @@ Comments.schema = new SimpleSchema({
>      type: String,
>      allowedValues: ["question", "vote"],
>    },
> +  source: {
> +    type: String,
> +    optional: true
> +  },
> +  source_data: {
>
> This should be a blackbox object
> ------------------------------
>
> In imports/api/facebook/comments/server/commentsHelpers.js
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497510350>
> :
>
> > +    check(facebookAccountId, String);
> +    check(entryId, String);
> +    check(accessToken, String);
> +    check(campaignId, String);
> +
> +    logger.debug("CommentsHelpers.getInstagramEntryComments called", { entryId });
> +
> +    const facebookAccount = FacebookAccountsHelpers.getFacebookAccount({facebookAccountId});
> +    const instagramBusinessAccountId = facebookAccount.instagramBusinessAccountId;
> +
> +    let commentedPeople = [];
> +
> +    const addCommentToBulk = ({ comment, bulk }) => {
> +      if (!comment.username) return;
> +      comment.source = 'instagram';
> +      comment.name = PeopleHelpers.getPersonName({ campaignId, instagramHandle: comment.username });
>
> We should be using the user_id provided by Instagram. The instagram
> handle cannot be considered an ID since it can be changed.
> ------------------------------
>
> In imports/api/facebook/entries/entries.js
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497510820>
> :
>
> > @@ -72,6 +72,38 @@ Entries.schema = new SimpleSchema({
>    },
>    "counts.share": {
>      type: Number
> +  },
> +  source: {
> +    type: String,
> +    optional: true
> +  },
> +  source_data: {
>
> This should be a blackbox object
> ------------------------------
>
> In imports/api/facebook/people/server/peopleHelpers.js
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497512548>
> :
>
> > @@ -733,6 +735,68 @@ const PeopleHelpers = {
>      // Update doc
>      return PeopleExports.update(exportId, { $set: { expired: true } });
>    },
> +  getPersonId({ campaignId, instagramHandle }) {
>
> We should use the user_id provided by Instagram. Instagram handle cannot
> be considered an ID
> ------------------------------
>
> In imports/ui2/pages/Comments.jsx
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#discussion_r497513951>
> :
>
> > @@ -27,6 +28,10 @@ const messages = defineMessages({
>    postFilter: {
>      id: "app.comments.entry_select_placeholder",
>      defaultMessage: "Filter by post..."
> +  },
> +  commentSourceFilter: {
> +    id: "app.comments.entry_select_placeholder",
>
> The i18n ID must be unique, something like
> app.comments.source_select_placeholder
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lianetoolkit/liane-toolkit/pull/166#pullrequestreview-499425796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHTBYZTUC2IGHH6XKHT3HODSIMYDHANCNFSM4R7BFA7A>
> .
>

2020-10-23 15:45 UTC, miguelpeixe commented
Manually merged into [epic/IG-3](/lianetoolkit/liane-toolkit/tree/epic/IG-3) with changes in 66c9d7460393686ec9b35097727ba443add24e70

2020-10-23 15:45 UTC, closed without merging