Giving the possibility to go to the comments section by the comment icons and placing for the tags to appear in the profile even when there is no
lianetoolkit/liane-toolkit pull request #200
Opened 2021-10-18 14:30 UTC by perospirone

this commit depends on https://github.com/lianetoolkit/liane-toolkit/pull/195

2021-11-12 00:59 UTC, miguelpeixe requested changes
The links are working well!

Left a few requests below. The `yarn.lock` and `package.json` files should be reverted for this merge.

For reference, here's how I'm seeing my People directory page with the new navigation options:

<img width="1327" alt="Captura de Tela 2021-11-11 às 21 50 41" src="https://user-images.githubusercontent.com/820752/141390518-d9b5fe2e-9eaa-4069-b019-70bfc1548a41.png">

2021-11-12 00:59 UTC, miguelpeixe commented on imports/ui2/components/PagePaging.jsx
> +          <button className="btn-pagination" onClick={() => {setLimit(20)}}>20</button>
The UI is not clear on the purpose of these buttons. I don't think it's necessary to allow the user to change this limit.

2021-11-12 00:59 UTC, miguelpeixe commented on package.json
> +    "bcrypt": "^5.0.1",
We don't need to address this dependency on this PR.

2021-11-14 18:28 UTC, danitw commented on imports/ui2/components/PagePaging.jsx
> +          <button className="btn-pagination" onClick={() => {setLimit(20)}}>20</button>
but they told me to do it, it was on my trial
about the ui: I asked for dart and he said it was good

2021-11-16 22:24 UTC, miguelpeixe commented on imports/ui2/components/PagePaging.jsx
> +          <button className="btn-pagination" onClick={() => {setLimit(20)}}>20</button>
This implementation is being applied to every view that uses the `PagePaging` component. This causes the Comments page to have buttons that doesn't trigger anything.

2022-01-14 21:26 UTC, eldardo commented on imports/ui2/components/PagePaging.jsx
> +          <button className="btn-pagination" onClick={() => {setLimit(20)}}>20</button>
Hi @danitw , the solution was good enough for the approval of the trial, but that does not necessarily imply direct integration into production. In addition, there were 3 different solutions with different quality results, mixed in the same pull request. I think we can close this one, and then check case by case the user stories, and before create other pull requests for each one.

2022-01-20 02:45 UTC, closed without merging